import site from '~/data/site.config.yml';
import { logoAscii } from '~/utils/logoAscii.js';

const buildTime = import.meta.env.BUILD_TIME;
const date = buildTime ? new Date(buildTime) : new Date();
const buildTime_formattedDate = date.toLocaleDateString('en-US', {
  year: 'numeric',
  month: 'long',
  day: 'numeric',
});

export async function GET() {
  const content = [
    '/* The humans responsible & colophon */',
    '/* humanstxt.org */',
    '',
    logoAscii,
    '',
    '',
    '/* AUTHOR */',
    `Name: ${site.author.name}`,
    `Email: ${site.author.email}`,
    `Github: 'https://github.com/'${site.author.social.github}`,
    `X: @${site.author.social.x}`,
    `Location: ${site.author.location}`,
    '',
    '/* SITE */',
    `Site Name: ${site.siteName}`,
    `Site URL: ${site.url}`,
    `Last update: ${buildTime_formattedDate}`,
    `Language: ${site.language.name}`,
    `Timezone: ${site.timezone}`,
    `Generated by: ${site.framework}`,
    `Hosted on: ${site.hosting}`,
  ].join('\n');

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
    },
  });
};
